eureka:
  instance:
    preferIpAddress: true
    leaseRenewalIntervalInSeconds: 1
    leaseExpirationDurationInSeconds: 3
  client:
    registryFetchIntervalSeconds: 1
    serviceUrl:
      defaultZone: http://localhost:8000/eureka/
turbine:
  app-config: